#/usr/bin/env sh

set -euo pipefail
IFS=$'\n\t'

mysql -uroot -hlocalhost -p"${MYSQL_ROOT_PASSWORD}" <<EOSQL
  CREATE USER IF NOT EXISTS '${MYSQL_TEST_USER}'@'%' IDENTIFIED BY '${MYSQL_TEST_PASSWORD}';
  CREATE DATABASE IF NOT EXISTS ${MYSQL_TEST_DATABASE};
  GRANT ALL PRIVILEGES ON ${MYSQL_TEST_DATABASE}.* TO '${MYSQL_TEST_USER}'@'%';
EOSQL

