#!/usr/bin/env ruby

require "sass"
require "sass/exec"

class Sass::Importers::Filesystem
  def extensions
    { 'sass' => :sass, 'scss' => :scss, 'css.sass' => :sass, 'css.scss' => :scss }
  end
end

if ARGV.empty?
  puts "Usage: ./script/compile_sass app/assets/stylesheets/application.css.scss > app.css"
  exit 0
else
  argv = %w(-I app/assets/stylesheets) + ARGV
  opts = Sass::Exec::Scss.new(argv)
  opts.parse!
end
